conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('<int:pk>/archive/', views.archive_conversation, name='archive_conversation'),
    path('<int:pk>/unarchive/', views.unarchive_conversation, name='unarchive_conversation'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('reviews/', include('reviews.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

conversation/models.py
from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth import get_user_model

from item.models import Item

class Conversation(models.Model):
    item = models.ForeignKey(Item, related_name='conversations', on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='conversations')
    archived_by = models.ManyToManyField(get_user_model(), blank=True, related_name='archived_conversations')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-modified_at',)
    
class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE)
    read = models.BooleanField(default=False)

conversation/forms.py
from django import forms

from .models import ConversationMessage

class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

conversation/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from item.models import Item
from .forms import ConversationMessageForm
from .models import Conversation, ConversationMessage
from django.contrib import messages
from django.db.models import Q

@login_required
def new_conversation(request, item_pk):
    item = get_object_or_404(Item, pk=item_pk)

    if item.created_by == request.user:
        return redirect('dashboard:index')
    
    conversations = Conversation.objects.filter(item=item).filter(members__in=[request.user.id])

    if conversations:
        return redirect('conversation:detail', pk=conversations.first().id)

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation = Conversation.objects.create(item=item)
            conversation.members.add(request.user)
            conversation.members.add(item.created_by)
            conversation.save()

            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.save()

            return redirect('item:detail', pk=item_pk)
    else:
        form = ConversationMessageForm()
    
    return render(request, 'conversation/new.html', {
        'form': form
    })

@login_required
def inbox(request):
    conversations = Conversation.objects.filter(members=request.user).exclude(archived_by=request.user)

    return render(request, 'conversation/inbox.html', {
        'conversations': conversations
    })

@login_required
def detail(request, pk):
    conversation = get_object_or_404(Conversation, pk=pk, members=request.user)
    # Mark all messages as read for this user
    conversation.conversationmessage_set.filter(~Q(created_by=request.user), read=False).update(read=True)
    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.conversation = conversation
            message.created_by = request.user
            message.save()
            return redirect('conversation:detail', pk=pk)
    else:
        form = ConversationMessageForm()
    return render(request, 'conversation/detail.html', {
        'conversation': conversation,
        'form': form
    })

@login_required
def archive_conversation(request, pk):
    conversation = get_object_or_404(Conversation, pk=pk, members=request.user)
    conversation.archived_by.add(request.user)
    messages.success(request, 'Conversation archived.')
    return redirect('conversation:inbox')

@login_required
def unarchive_conversation(request, pk):
    conversation = get_object_or_404(Conversation, pk=pk, members=request.user)
    conversation.archived_by.remove(request.user)
    messages.success(request, 'Conversation unarchived.')
    return redirect('conversation:inbox')

conversation/templates/conversation/detail.html
{% extends 'core/base.html' %}{% block title %}Conversation{% endblock %}{%
block content %}
<h1 class="mb-6 text-3xl">Conversation</h1>
<div class="space-y-6">
  {% for message in conversation.conversationmessage_set.all %}
  <div
    class="p-6 flex {% if message.created_by == request.user %}bg-blue-100{% else %}bg-gray-100{% endif %} rounded-xl"
  >
    <div>
      <p class="mb-4">
        <strong>{{ message.created_by.username }}</strong> @ {{
        message.created_at }}{% if not message.read and message.created_by !=
        request.user %}<span class="ml-2 text-xs text-red-500">Unread</span>{%
        endif %}
      </p>
      <p>{{ message.content }}</p>
    </div>
  </div>
  {% endfor %}
</div>
<form method="post" action="." class="mt-6">
  {% csrf_token %}{{ form.as_p }}<button
    class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"
  >
    Send
  </button>
</form>
{% if request.user in conversation.archived_by.all %}
<form
  method="post"
  action="{% url 'conversation:unarchive_conversation' conversation.id %}"
  class="mt-4"
>
  {% csrf_token %}<button
    type="submit"
    class="text-sm text-teal-500 hover:underline"
  >
    Unarchive Conversation
  </button>
</form>
{% else %}
<form
  method="post"
  action="{% url 'conversation:archive_conversation' conversation.id %}"
  class="mt-4"
>
  {% csrf_token %}<button
    type="submit"
    class="text-sm text-red-500 hover:underline"
  >
    Archive Conversation
  </button>
</form>
{% endif %}{% endblock %}

conversation/templates/conversation/new.html
{% extends 'core/base.html' %} {% block title %}New conversation{% endblock %}
{% block content %}
<h1 class="mb-6 text-3xl">New conversation</h1>
<form method="post" action=".">
  {% csrf_token %}
  <div class="space-y-4">{{ form.as_p }}</div>
  {% if form.errors or form.non_field_errors %}
  <div class="mb-3 p-6 bg-red-100 rounded-xl">
    {% for field in form %}{{ field.errors }}{% endfor %}{{
    form.non_field_errors }}
  </div>
  {% endif %}
  <button
    class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white"
  >
    Send
  </button>
</form>
{% endblock %}